### PR TITLE
move states up to the module's scope

### PR DESCRIPTION
**Pull request by yonantan**

### CODE REVIEW

**Comment by dimapaloskin** [comment]
Hm, what the reason for this moving?

**Comment by yonantan** [comment]
@dimapaloskin 
supporting multiple/different instances for each of the routes `/facebook` and `/facebook/callback` for example, in case you want to use `micro-router` and dynamically instantiate `microauth-facebook` with different params.

otherwise, `Invalid state` is thrown, which seems unintentional for that particular scenario.

**Comment by dimapaloskin** [comment]
I think sharing state between several instances of `facebookAuth` instances is bad idea. Especially if they have **different** setup. 

Could you provide a part of code and we will try to think of something which can help you :)

**Comment by yonantan** [comment]
I don't agree that it's a bad idea.
Could you please give an example that would be negatively affected by this?

according to Facebook's docs:
> state: An arbitrary unique string created by your app to guard against Cross-site Request Forgery.

since the states object can only be shared by instances of **the same module**, we don't need to worry about Cross-site Request Forgery in this regard...

**Comment by dimapaloskin** [comment]
Just an example:

server1.js

```js
const micro = reuqire('micro')

// fb stuff here

const server = micro(...)
server.listen(3000)
```
server2.js
```js
const micro = reuqire('micro')

// fb stuff here

const server = micro(...)
server.listen(4000)
```

index.js

```
const s1 = require('./server1')
const s2 = require('./server2')
```

In this case state will be shared between two **different** servers. But it is unexpected.

What do you think about this?

**Pull request closed without merging**
